### ISSUE TITLE
If you configure wrong mqtt credentials, the add-on won't start and you can't configure them anymore

### ISSUE THREAD

**Issue by thjr** [balda/ruuvitag-discovery#13]
Log:

`Start RuuviTag Discovery - v0.1.13
Start measures sampling every 10 seconds
Start web server on port 8099
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/app/node_modules/mqtt/lib/client.js:1076:15)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:365:12)
    at work (/app/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:728:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
Emitted 'error' event on MqttClient instance at:
    at MqttClient._handleConnack (/app/node_modules/mqtt/lib/client.js:1078:10)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:365:12)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:309:12) {
  code: 5
}
[cmd] node exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... `

**Comment by balda** [comment]
Thanks for submitting this bug! (I has encountered it myself).
I'm currently rewrite a lot of things and I have planned to bugfix this in next release.

**Comment by balda** [comment]
Done in release `0.2.0`
