### ISSUE TITLE
second npm start error should be more friendly - 0.2.0 -enhancement

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#27]
I like ruuvitag-discovery so much I tried to start it a second time while it was already running. (actually the currently running instance was  obscured by another terminal window).
This should report something like. "I'm already running" 
rather than  the very ugly:
events.js:287
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE: address already in use :::8099
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.listen (/Volumes/DATA/dgerman/Documents/computerstuff/phyweb/ruuvi/discovery-0.2.0/node_modules/express/lib/application.js:618:24)
    at Object.start (/Volumes/DATA/dgerman/Documents/computerstuff/phyweb/ruuvi/discovery-0.2.0/lib/server.js:78:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/Volumes/DATA/dgerman/Documents/computerstuff/phyweb/ruuvi/discovery-0.2.0/index.js:328:5)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (events.js:310:20)
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8099

**Comment by balda** [comment]
Now, you should have a more friendly error message ;)

```bash
[Error] web server port 8099 already in use: you can't use a same port more than once.
```

And you can run a second server now: I added an env variable to change the server port (you can only have one service by port: more is forbidden).

Usage: `SERVER_PORT=8100 npm start`
