### ISSUE TITLE
TypeError while broadcasting to mqtt

### ISSUE THREAD

**Issue by thjr** [balda/ruuvitag-discovery#5]
Hello

I got the following error, which killed the add-on:
```
MQTT "Embedded MQTT" disconnected
Connected to MQTT "Embedded MQTT"
/app/lib/broadcast/ha_mqtt.js:30
            ids: `ruuvitag-${tag.id}`,
                                 ^

TypeError: Cannot read property 'id' of undefined
    at present (/app/lib/broadcast/ha_mqtt.js:30:34)
    at Object.broadcaster.send (/app/lib/broadcast/ha_mqtt.js:104:13)
    at broadcast (/app/index.js:69:25)
    at Timeout._onTimeout (/app/index.js:194:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[cmd] node exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by balda** [comment]
It should be "fixed" in release `0.1.11`.
But i havent' tested HA embedded mqtt, so i don't know if it disconnect some times or not.
I close the issue, but if you have some troubles with mqtt, re-open it ;)
